language: csharp
solution: DomainNameGenerator.sln
install:
  - nuget restore DomainNameGenerator.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DomainNameGenerator.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DomainNameGeneratorTests/bin/Release/DomainNameGeneratorTests.dll